services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "8085:8080"
    depends_on:
      - kafka
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Postgres cho Airflow Metadata
  postgres:
    image: postgres:13
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  # HADOOP HDFS (Storage Layer)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8 
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870" 
      - "9000:9000" 
    volumes:
      - hadoop_namenode:/hadoop/dfs/name 
      - ./data:/data/local_input
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000 
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
      - HDFS_CONF_dfs_replication=2

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8 
    container_name: datanode1
    hostname: datanode1
    restart: always
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data 
      - ./data:/data/local_input
    environment:
      - SERVICE_PRECONDITION=namenode:9870 
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8 
    container_name: datanode2
    hostname: datanode2
    restart: always
    ports:
      - "9865:9864"
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data 
      - ./data:/data/local_input
    environment:
      - SERVICE_PRECONDITION=namenode:9870 
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000 
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
    depends_on:
      - namenode

  # HIVE DWH 
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-db 
    hostname: hive-metastore-db
    volumes:
      - hive_postgresql:/var/lib/postgresql/data

  # Hive Metastore
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore 
    container_name: hive-metastore
    hostname: hive-metastore
    # Sử dụng env_file để nạp các biến HDFS/DB (nếu cần)
    # env_file:
    #   - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      - SERVICE_PRECONDITION=namenode:9000 hive-metastore-db:5432
      - DB_DRIVER=postgresql
      - DATABASE_TYPE_JDBC_URL=jdbc:postgresql://hive-metastore-db:5432/metastore
      - DATABASE_USER=hive
      - DATABASE_PASSWORD=hive
    ports:
      - "9083:9083"
    volumes:
      - ./infrastructure/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml 
      - ./src/hive/warehouse:/opt/hive/data/warehouse 
    depends_on:
      - hive-metastore-postgresql
      - namenode 

  # Hive Server
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    hostname: hive-server
    environment:
      - SERVICE_PRECONDITION=hive-metastore:9083
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./src/hive/warehouse:/opt/hive/data/warehouse 
      - ./infrastructure/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml 
      - ./scripts:/opt/hive/scripts
      - ./data:/data
    depends_on:
      - hive-metastore

  # SPARK
  spark-master:
    build:
        context: .
        dockerfile: infrastructure/docker/Dockerfile.spark
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./src/streaming:/opt/bitnami/spark/streaming
      - ./src/schema:/opt/bitnami/spark/schema
      - ./utils:/opt/bitnami/spark/utils
      - ./data:/opt/bitnami/spark/data
      - ./config:/opt/bitnami/spark/conf
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - namenode

  spark-worker1:
    build:
        context: .
        dockerfile: infrastructure/docker/Dockerfile.spark
    hostname: spark-worker1
    ports:
      - "8082:8081"
    environment:
      - KAFKA_BROKER_URL=kafka:29092 
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./src/streaming:/opt/bitnami/spark/streaming
      - ./utils:/opt/bitnami/spark/utils
      - ./data:/opt/bitnami/spark/data
      - ./config:/opt/bitnami/spark/conf
    depends_on:
      - spark-master

  spark-worker2:
    build:
        context: .
        dockerfile: infrastructure/docker/Dockerfile.spark
    hostname: spark-worker2
    ports:
      - "8084:8081"
    environment:
      - KAFKA_BROKER_URL=kafka:29092 
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./src/streaming:/opt/bitnami/spark/streaming
      - ./utils:/opt/bitnami/spark/utils
      - ./data:/opt/bitnami/spark/data
      - ./config:/opt/bitnami/spark/conf
    depends_on:
      - spark-master

  # export KAFKA_BROKER_URL=kafka:29092
  # export SCHEMA_REGISTRY_URL=http://schema-registry:8081
  #spark-submit --master spark://spark-master:7077 /opt/bitnami/spark/streaming/weather_stream.py
  spark-submit:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.spark
    depends_on:
    - spark-master
    - spark-worker1
    - spark-worker2
    environment:
      - KAFKA_BROKER_URL=kafka:29092 
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - BRONZE_LAYER_PATH=${BRONZE_LAYER_PATH}
      - SILVER_LAYER_PATH=${SILVER_LAYER_PATH}
      - GOLD_LAYER_PATH=${GOLD_LAYER_PATH}
    volumes:
      - ./src/streaming:/opt/bitnami/spark/streaming
      - ./utils:/opt/bitnami/spark/utils
      - ./data:/opt/bitnami/spark/data
      - ./config:/opt/bitnami/spark/conf
    command: >
      spark-submit
      --master spark://spark-master:7077
      /opt/bitnami/spark/streaming/weather_stream.py

  realtime-producer:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.base
    hostname: realtime-producer
    container_name: realtime-producer
    environment:
      - KAFKA_BROKER_URL=kafka:29092 
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - FOOTBALL_DATA_API_KEY=${FOOTBALL_DATA_API_KEY}
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./src/ingestion:/opt/airflow/ingestion
      - ./src/schema:/opt/airflow/schema
      - ./utils:/opt/airflow/utils
    depends_on:
      - kafka
      - schema-registry
    command: python /opt/airflow/ingestion/api/streaming.py

  email-alert-consumer:
    build:
      context: .
      dockerfile: src/streaming/email-alert/Dockerfile
    environment:
      - KAFKA_BROKER_URL=kafka:29092 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - RECIPIENT_EMAILS=${RECIPIENT_EMAILS}
    depends_on:
      - redis
      - kafka
    

  airflow-init:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.base
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow
    entrypoint: ["bash", "-c"]
    command: ["airflow db init"]
    depends_on:
      - postgres

  airflow-webserver:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.base 
    hostname: airflow-webserver
    ports:
      - "8083:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src/ingestion:/opt/airflow/ingestion
      - ./utils:/opt/airflow/utils
      - ./data:/data 
      - ./logs:/opt/airflow/logs 
      - ./infrastructure/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml 
    depends_on:
      - postgres
      - redis
      - airflow-init
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.base
    hostname: airflow-scheduler
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src/ingestion:/opt/airflow/ingestion
      - ./src/batch:/opt/airflow/batch
      - ./utils:/opt/airflow/utils
      - ./data:/data 
      - ./logs:/opt/airflow/logs 
      - ./infrastructure/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml 
    depends_on:
      - postgres
      - redis
      - airflow-init
    command: scheduler

volumes:
  zookeeper_data:
  kafka_data:
  redis_data:
  postgres_data:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hive_metastore_data:
  hive_postgresql:
  # nifi_data:
  # nifi_logs:
  # elasticsearch_data:
  # prometheus_data:
  # grafana_data: